"""empty message

Revision ID: a5a6216e96ff
Revises: 
Create Date: 2022-04-21 17:48:04.334375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a6216e96ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deger', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veri')
    # ### end Alembic commands ###
